### ISSUE TITLE
Автозагрузка класса

### ISSUE THREAD

**Issue by sergejkaravajnij** [korytoff/PHP-TimeHelper#13]
Привет!

Подключил твой в проект yii2 через композер.
Класс скачивается в папку `/vendor/korytoff/timehelper`
а неймспейс в классе namespace `korytoff\helpers;`

Когда хочу использовать твой класс указываю `use korytoff\helpers\TimeHelper;`
но автолоадер не работает.

Удалось запустить через автолоадер, только если переименовать папку timehelper в helpers =
`/vendor/korytoff/helpers` и прописал алиас в настройку приложения `'@korytoff' => '@vendor/korytoff/'`

Мне кажется, что если что-то где-то поправить, то все заработает само, но я не очень силен во всех этих PSR...

Вообщем, это мне у себя что-то править или можно что-то сделать в репозитории, чтобы автолоадер работал?

**Comment by korytoff** [comment]
Привет, вообще я в `composer.json` указывал конфиг для автолоадера, странно что у тебя не подключился. Может из-за того, что PSR-0 считается устаревшим и у тебя свежий composer.
